### PR TITLE
Links

### PR DESCRIPTION
**Pull request by jhack32**
Changes proposed in this pull request:

### CODE REVIEW

**Comment by dijonkitchen** [comment]
Repeat of #37?

**Comment by jhack32** [comment]
This just needs a rebase

**Comment by dijonkitchen** [comment]
But all the commits are the same in both.

**Comment by jhack32** [comment]
It might be because I created the branch off of contact. What I meant by it just needs a rebase is, rebasing it after the contact branch is merged.

**Comment by dijonkitchen** [comment]
Time for rebase? @jhack32

**Review by dijonkitchen — APPROVED** [review]

**Review by aattsai — APPROVED** [review]

**Pull request merged**
