### PR TITLE
Add text descriptions

### PR DESCRIPTION
**Pull request by dijonkitchen**
Changed 'services' to 'values' since it shows our values and what we can do for
them.

Includes a few short paragraphs on values and our team.

### CODE REVIEW

**Comment by aattsai** [comment]
Do we need a section (what I had in mind for services) where we describe exactly what we provide? ie. UI/UX design, Web development, mobile app development, marketing/SEO...

**Comment by dijonkitchen** [comment]
Sure we can detail it.

**Comment by aattsai** [comment]
👍

**Comment by jhack32** [comment]
👍

**Pull request merged**
